batch_size: 64
model: DeepSnake
model_args:
  backbone: SlimResNet18
  model_dim: 512
  iterations: 3
  subdivide: false
  weight_sharing: true
  coord_features: true
loss_function: SoftDTW(0.001)
data_root: '../aicore/uc1/data'
data_size: 128
bands:
  - SPECTRAL/BANDS/STD_2s_B8_8b
vertices: 33
