backbone: ResNet18
model: DeepSnake
weights: 3krx3b01-best
fixed_weights: head
head:
  subdivide: true
  coord_features: true
  weight_sharing: false
  width: 512
  iterations: 5
loss_function: SoftDTW(0.001)
data_root: '../aicore/uc1/data'
data_size: 128
bands:
  - SPECTRAL/BANDS/NORM_B2_8b
  - SPECTRAL/BANDS/NORM_B3_8b
  - SPECTRAL/BANDS/NORM_B4_8b
  - SPECTRAL/BANDS/NORM_B4_8b
  - DEM/bed_30m
  - DEM/elevation_ortho_30m
  - TEXTURE/GLCM/11x11_ASM
  - TEXTURE/GLCM/11x11_CON
  - TEXTURE/GLCM/11x11_COR
  - TEXTURE/GLCM/11x11_DIS
  - TEXTURE/GLCM/11x11_ENT
  - TEXTURE/GLCM/11x11_HOM
vertices: 65
