baseURL: https://khdlr.github.io/COBRA/
languageCode: en-gb
title: COBRA
theme: "PaperMod"
enableRobotsTXT: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  defaultTheme: auto
  env: production
  title: COBRA
  author: Konrad Heidler
  DateFormat: "2 Jan 2006"
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: true

  profileMode:
    enabled: true
    title: "Konrad Heidler" # optional default will be site title
    content: "Teaching computers how to understand satellite imagers."
    subtitle: "Teaching computers how to understand satellite images."
    imageUrl: "profile.jpg" # optional
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Research
        url: "/research"
      - name: Posts
        url: "/posts"
  socialIcons:
    - name: "googlescholar"
      url: "https://scholar.google.de/citations?user=RF9yl6sAAAAJ&hl=en"
    - name: "researchgate"
      url: "https://www.researchgate.net/profile/Konrad-Heidler"
    - name: "github"
      url: "https://github.com/khdlr"
    - name: "twitter"
      url: "https://twitter.com/koheidler"
    - name: "youtube"
      url: "https://www.youtube.com/channel/UCR2GEzwX16leeQT1keX3ESg"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/kheidler/"
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page
menu:
  main:
    - identifier: research
      name: research
      url: /research/
      weight: 5
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
  # - identifier: categories
  #   name: categories
  #   url: /categories/
  #   weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
