# Model Specification

model: DeepSnake
model_args:
  backbone: Xception
  model_dim: 1024
  iterations: 4
  coord_features: true
  stop_grad: true
  weight_sharing: true
  head: SnakeHead
loss_function: stepwise(l1_loss)

# Data args
batch_size: 16
data_root: '../CALFIN/training/data'
data_channels: [2]
# data_root: '../aicore/uc1/data/'
# data_channels:
#   - 'SPECTRAL/BANDS/STD_2s_B8_8b'
tile_size: 256
vertices: 64
