# Model Specification
model: DeepSnake
model_args:
  backbone: SlimResNet18
  model_dim: 512
  iterations: 5
  subdivide: false
  weight_sharing: true
  coord_features: true
loss_function: SoftDTW(0.001)
# Data args
batch_size: 64
data_root: '../CALFIN/training/data'
tile_size: 256
vertices: 65
