# Model Specification
model: DeepSnake
model_args:
  backbone: ResNet50
  model_dim: 1024
  iterations: 5
  coord_features: true
  stop_grad: true
loss_function: SoftDTW(0.001)
# Data args
batch_size: 32
data_root: '../CALFIN/training/data'
tile_size: 256
vertices: 64
