batch_size: 64
backbone: SlimResNet18
model: DeepSnake
head:
  subdivide: true
  coord_features: true
  weight_sharing: false
  width: 256
  iterations: 4
loss_function: SoftDTW(0.001)
data_root: '../aicore/uc1/data'
data_size: 128
bands:
  - SPECTRAL/BANDS/STD_2s_B8_8b
vertices: 33
