backbone: ResNet18
model: DeepSnake
weights: 3krx3b01-best
fixed_weights: head
head:
  subdivide: true
  coord_features: true
  weight_sharing: false
  width: 512
  iterations: 5
loss_function: SoftDTW(0.001)
data_root: '../uc1/data'
data_size: 128
bands:
  - SPECTRAL/BANDS/NORM_B2_8b
  - SPECTRAL/BANDS/NORM_B3_8b
  - SPECTRAL/BANDS/NORM_B4_8b
vertices: 65
